### ISSUE TITLE
newbie failed to use

### ISSUE THREAD

**Issue by ruimmpires** [teriyakichild/zabbixhistory2csv#3]
Traceback (most recent call last):
  File "zabbixhistory2csv.py", line 168, in <module>
    write_csv(results, args.output_file)
  File "zabbixhistory2csv.py", line 84, in write_csv
    f.writerow(objects[0].keys())
TypeError: a bytes-like object is required, not 'str'

Seems a wrong type in:
def write_csv(objects, output_file):
    """
    :param objects:
    :param output_file:
    :return:
    """
    # Open the output_file and instanstiate the csv.writer object
    f = csv.writer(open(output_file, "wb+"))
    # Write the top line of the output_file which describes the columns
    f.writerow(objects[0].keys())
    # Write the results to file in csv format
    write_csv(results, args.output_file)

**Comment by zhang12c** [comment]
我也遇到统一的问题

**Comment by zhang12c** [comment]
Traceback (most recent call last):
  File "zabbixhistory2csv\zabbixhistory2csv.py", line 169, in <module>
    write_csv(results, args.output_file)
  File "zabbixhistory2csv\zabbixhistory2csv.py", line 86, in write_csv
    f.writerow(objects[0].keys())
TypeError: a bytes-like object is required, not 'str'
